fix = false
line-length = 88  # Same as black
respect-gitignore = true

[format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[lint]
select = [
    "YTT",  # flake8-2020 rules (for sys.version)
    "ANN",  # flake8-annotations rules
    "A",    # flake8-builtins rules (for builtin shadowing)
    "C4",   # flake8-comprehensions rules
    "PT",   # flake8-pytest-style rules
    "Q",    # flake8-quotes rules
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib (instead of os.path)
    "PD",   # pandas-vet
    "N",    # pep8-naming
    "E1",   # spaces and tabs
    "E2",   # whitespace padding
    "E3",   # blank lines
    "E4",   # imports
    "E7",   # statements
    "E9",   # io error
    "W5",   # doc line length
    "F",    # pyflakes
    ]
task-tags = ["TODO", "FIXME", "XXX"]
